export const exifFields: { key: string; name: string; value: "", show?: boolean }[] = [
	{ key: "Make", name: "Logo", value: "", show: true },
	{ key: "Model", name: "型号", value: "", show: true },
	{ key: "LensMake", name: "镜头Logo", value: "", show: true },
	{ key: "LensModel", name: "镜头型号", value: "", show: true },
	{ key: "LensSpecification", name: "镜头规格", value: "", show: true },
	{ key: "ExposureTime", name: "快门", value: "", show: true },
	{ key: "FNumber", name: "光圈", value: "", show: true },
	{ key: "ISOSpeedRatings", name: "ISO", value: "", show: true },
	{ key: "FocalLength", name: "焦距", value: "", show: true },
	{ key: "FocalLengthIn35mmFilm", name: "等效焦距", value: "", show: true },
	{ key: "ExposureProgram", name: "档位", value: "", show: true },
	{ key: "ExposureMode", name: "曝光补偿", value: "", show: true },
	{ key: "MeteringMode", name: "测光模式", value: "", show: true },
	{ key: "WhiteBalance", name: "白平衡", value: "", show: true },
	{ key: "DateTimeOriginal", name: "拍摄日期", value: "", show: true },
	{ key: "Image Height", name: "图片高度", value: "", show: false },
	{ key: "Image Width", name: "图片宽度", value: "", show: false },

];
